apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dns-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dns-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DUCKDNS_TOKEN: "{{.TOKEN}}"
  dataFrom:
    - extract:
        key: duckdns
