---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-34.2.1+up34.2.0.tgz
  failurePolicy: reinstall
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    additionalArguments:
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${CLUSTER_DOMAIN}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${CLUSTER_DOMAIN}"
    persistence:
      enabled: true
      size: 128Mi
    certificatesResolvers:
      letsencrypt:
        acme:
          email: "vikaspoguadf@gmail.com"
          caServer: https://acme-v02.api.letsencrypt.org/directory # Production server
          dnsChallenge:
            provider: duckdns
            propagation:
              disableChecks: true
              delayBeforeChecks: 60
            resolvers:
              - 8.8.8.8
              - 1.1.1.1
          storage: /data/acme.json
    envFrom:
      - secretRef:
          name: dns-token
    deployment:
      podAnnotations:
        prometheus.io/port: "8082"
        prometheus.io/scrape: "true"
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
          volumeMounts:
            - name: data
              mountPath: /data
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      repository: "rancher/mirrored-library-traefik"
      tag: "3.3.6"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      ipFamilyPolicy: "PreferDualStack"
