---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-secret
  namespace: ldap-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ldap-secret
    creationPolicy: Owner
  data:
    - secretKey: bindPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: lldap
        property: LLDAP_LDAP_USER_PASS
        metadataPolicy: None
