apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: test-team-a
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: proxmox/team-a-kubernetes
          role: team-a-secret-reader
          serviceAccountRef:
            name: default
      path: "proxmox/team-a-kubernetes"
      server: "http://vault.vault.svc.cluster.local:8200"
      version: v1
