apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: developer-hub
  namespace: developer-hub
spec:
  authentication:
    namespace: vault-admin
    path: kubernetes
    role: policy-admin
  type: kv
  path: proxmox
