---
controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/syncthing/syncthing
          tag: 2.0.7@sha256:9f78e172614132f96befeec5c857164222df0da99aaf7620355c2d5d8ce09dac
        env:
          TZ: America/New_York
          PGID: 0
          PUID: 0
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /rest/noauth/health
                port: &port 8384
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            memory: 250Mi
        securityContext:
          allowPrivilegeEscalation: true
  defaultPodOptions:
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: OnRootMismatch
service:
  app:
    forceRename: syncthing
    primary: true
    ports:
      http:
        port: *port
  sync:
    ports:
      discovery:
        port: 21027
        protocol: UDP
      listen-tcp:
        port: 22000
        protocol: TCP
      listen-udp:
        port: 22000
        protocol: UDP
persistence:
  config:
    type: hostPath
    hostPath: /storage0/syncthing/config
    globalMounts:
      - path: "/var/syncthing"
  data:
    type: hostPath
    hostPath: /storage0/syncthing/data
    globalMounts:
      - path: /data
