---
controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/syncthing/syncthing
          tag: 2.0.8@sha256:f987f753d468b609734363b4984dc7ccee85ecaf8240c7293fb318a43a38f1df
        env:
          TZ: America/New_York
          PGID: 0
          PUID: 0
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /rest/noauth/health
                port: &port 8384
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: true
          runAsNonRoot: false
          runAsUser: 0
          runAsGroup: 0
service:
  app:
    forceRename: syncthing
    primary: true
    ports:
      http:
        port: *port
  sync:
    ports:
      discovery:
        port: 21027
        protocol: UDP
      listen-tcp:
        port: 22000
        protocol: TCP
      listen-udp:
        port: 22000
        protocol: UDP
persistence:
  config:
    type: hostPath
    hostPath: /srv/dev-disk-by-uuid-9d2e4cb9-8825-4168-8153-e020ee524474/storage0/syncthing/config
    globalMounts:
      - path: "/var/syncthing"
  data:
    type: hostPath
    hostPath: /srv/dev-disk-by-uuid-9d2e4cb9-8825-4168-8153-e020ee524474/storage0/syncthing/data
    globalMounts:
      - path: /data
