---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./rbac.yaml

helmCharts:
  - name: reflector
    releaseName: reflector
    namespace: reflector
    repo: https://emberstack.github.io/helm-charts
    version: "9.0.318"
    valuesInline:
      nameOverride: reflector
      fullnameOverride: reflector
