---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vm-ssh-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vm-ssh-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        key: "{{.SSH_KEY}}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: vm-user-password
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vm-user-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vm-user-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: vm-user-password
        metadataPolicy: None
