---
- name: Load encrypted credentials
  community.sops.load_vars:
    file: secret.sops.yml
    expressions: ignore

- name: Include initial VM setup task
  include: vm-setup.yaml
  tags:
    - vm-setup

- name: Include task to create Apache2,TFTP,HAProxy
  include: apache2-tftp-haproxy.yaml
  tags:
    - apache2-tftp-haproxy

- name: Include task to setup PXE boot with ignition
  include: pxe-ignition.yaml
  tags:
    - pxe-ignition

- name: Include task to setup nfs server
  include: nfs-server.yaml
  tags:
    - nfs-server

- name: Get absolute path to this Git repository
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.command: "git rev-parse --show-toplevel"
  register: repo_abs_path

- name: Copy kubeadmin to provision folder
  ansible.builtin.fetch:
    src: "/root/ocp4/auth/kubeadmin-password"
    dest: "{{ repo_abs_path.stdout }}/provision/kubeadmin-password"
    flat: true
