---
- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"
  when:
    - timezone is defined

- name: Add user to sudoers
  ansible.builtin.copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    mode: "0440"

- name: Disable IPv6
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Add additional user SSH public keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  with_items:
    - "{{ ssh_authorized_keys }}"
  when:
    - ssh_authorized_keys is defined
    - ssh_authorized_keys is iterable
    - ssh_authorized_keys | length > 0

- name: generate SSH key
  openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no

- name: Install packages
  apt:
    name:
      - "{{ item }}"
    state: present
  loop: "{{ infra.packages }}"
  register: apt_install_common
  retries: 10
  until: apt_install_common is success

- name: Open up firewall ports
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}"
  loop: "{{ infra.ports }}"
  run_once: true
