---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: github
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .GH_TOKEN }}"
  dataFrom:
    - extract:
        key: developer-hub
