---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml

helmCharts:
  - name: operators-installer
    releaseName: metallb-operator
    namespace: metallb-system
    repo: https://redhat-cop.github.io/helm-charts
    version: "3.1.0"
    valuesInline:
      operators:
        - channel: stable
          installPlanApproval: Manual
          name: metallb-operator
          source: redhat-operators
          sourceNamespace: openshift-marketplace
          csv: metallb-operator.v4.17.0-202501081435
      operatorGroups:
        - createNamespace: false
