---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml

helmCharts:
  - name: operators-installer
    releaseName: metallb-operator
    namespace: metallb-system
    repo: https://redhat-cop.github.io/helm-charts
    version: "3.2.4"
    valuesInline:
      operators:
        - channel: <REPLACE>
          installPlanApproval: Manual
          name: metallb-operator
          source: redhat-operators
          sourceNamespace: openshift-marketplace
          csv: <REPLACE>
      operatorGroups:
        - createNamespace: false
