---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh-operator
  namespace: rhdh-operator
spec:
  channel: fast
  installPlanApproval: Manual
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
