---
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: proxmox
rendezvousIP: 10.30.30.100
hosts:
  - hostname: master-0
    interfaces:
      - name: ens18
        macAddress: 52:50:56:11:22:11
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: 52:50:56:11:22:11
          ipv4:
            enabled: true
            address:
              - ip: 10.30.30.100
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.30.0.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.30.30.1
            next-hop-interface: ens18
            table-id: 254
  - hostname: master-1
    interfaces:
      - name: ens18
        macAddress: 52:50:56:11:22:22
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: 52:50:56:11:22:22
          ipv4:
            enabled: true
            address:
              - ip: 10.30.30.101
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.30.0.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.30.30.1
            next-hop-interface: ens18
            table-id: 254
  - hostname: master-2
    interfaces:
      - name: ens18
        macAddress: 52:50:56:11:22:33
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: 52:50:56:11:22:33
          ipv4:
            enabled: true
            address:
              - ip: 10.30.30.102
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.30.0.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.30.30.1
            next-hop-interface: ens18
            table-id: 254
