---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
resources:
  - ./argocd.yaml
  - ./cluster-rolebinding.yaml
  - ./plugin-configmap.yaml
  - ./setenv-cmp-plugin.yaml
