---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Delete=false
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
  name: openshift-gitops
