---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Delete=false
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-gitops
