---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth-cert
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  labels:
    {{- include "hcp-cluster-deployment.labels" . | nindent 4 }}
spec:
  secretName: oauth-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - oauth-{{ .Values.clusterName }}-{{ .Values.clusterName }}.apps.proxmox.{{ .Values.baseDomain }}
