---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-user-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: aap-user-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .USER_TOKEN }}"
        host: "{{ .HOST }}"
        verify_ssl: "false"
  dataFrom:
    - extract:
        key: aap
