applications:
  external-secrets-chart:
    annotations:
      argocd.argoproj.io/sync-wave: "5"
    destination:
      namespace: external-secrets
    source:
      path: components/external-secrets-chart

  onepassword-connect-chart:
    annotations:
      argocd.argoproj.io/sync-wave: "10"
    destination:
      namespace: external-secrets
    source:
      path: components/onepassword-connect-chart

  argocd-chart:
    annotations:
      argocd.argoproj.io/sync-wave: "15"
    destination:
      namespace: argocd-app
    source:
      path: components/argocd-chart

  traefik-chart:
    annotations:
      argocd.argoproj.io/sync-wave: "15"
    destination:
      namespace: kube-system
    source:
      path: components/traefik-chart

  rancher-ui:
    annotations:
      argocd.argoproj.io/sync-wave: "25"
    destination:
      namespace: rancher-app
    source:
      path: components/rancher-ui

  garage-app:
    annotations:
      argocd.argoproj.io/sync-wave: "25"
    destination:
      namespace: default
    source:
      path: components/garage-app

  bytestash:
    annotations:
      argocd.argoproj.io/sync-wave: "25"
    destination:
      namespace: default
    source:
      path: components/bytestash

  homepage:
    annotations:
      argocd.argoproj.io/sync-wave: "25"
    destination:
      namespace: default
    source:
      path: components/homepage

  syncthing:
    annotations:
      argocd.argoproj.io/sync-wave: "25"
    destination:
      namespace: default
    source:
      path: components/syncthing

  reloader:
    annotations:
      argocd.argoproj.io/sync-wave: "25"
    destination:
      namespace: default
    source:
      chart: reloader
      repoURL: ghcr.io/stakater/charts
      targetRevision: 2.2.0
      helm:
        releaseName: sealed-secrets
        valuesObject:
          fullnameOverride: reloader
          reloader:
            readOnlyRootFileSystem: true
            podMonitor:
              enabled: true
              namespace: "{{ .Release.Namespace }}"
