apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../helm/charts

helmCharts:
  - name: argocd-app-of-app
    valuesInline:
      default:
        app:
          enabled: true
          enableAutoSync: true
          autoSyncPrune: true
          project: default
          labels:
            app-source: cluster-omv
            repo: default
          destination:
            namespace: argocd-app
            server: https://kubernetes.default.svc
          source:
            repoURL: https://github.com/Vikaspogu/openshift-multicluster.git
            targetRevision: HEAD
          syncOptions:
            - ApplyOutOfSyncOnly=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
            - ServerSideApply=true
            - FailOnSharedResource=true
            - RespectIgnoreDifferences=true
            - CreateNamespace=false
          syncPolicyRetry:
            limit: -1
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 10m
    additionalValuesFiles:
      - ./applications.yaml
    namespace: argocd-app

patches: []
