---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubechecks
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kubechecks
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KUBECHECKS_VCS_TOKEN: "{{ .GH_TOKEN }}"
        KUBECHECKS_ARGOCD_API_TOKEN: "{{.ARGOCD_TOKEN}}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: developer-hub
        metadataPolicy: None
