---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubechecks
resources:
  - ./namespace.yaml
  - ./externalsecret.yaml

helmCharts:
  - name: kubechecks
    releaseName: kubechecks
    namespace: kubechecks
    repo: https://zapier.github.io/kubechecks/
    version: "0.5.5"
    valuesFile: values.yaml
