apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubechecks-scc-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: kubechecks
    namespace: kubechecks
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubechecks-gitops-ns-admin
  namespace: openshift-gitops
subjects:
  - kind: ServiceAccount
    name: kubechecks
    namespace: kubechecks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
