# Labels to apply to all resources created by this Helm chart
argocd:
  namespace: openshift-gitops

commonLabels: {}

configMap:
  create: true
  env:
    KUBECHECKS_ADDITIONAL_APPS_NAMESPACES: "*"
    KUBECHECKS_ARGOCD_API_INSECURE: "true"
    KUBECHECKS_ARGOCD_API_NAMESPACE: openshift-gitops
    KUBECHECKS_ARGOCD_API_SERVER_ADDR: openshift-gitops-server.openshift-gitops.svc.cluster.local:80
    KUBECHECKS_ARGOCD_WEBHOOK_URL: http://openshift-gitops-server.openshift-gitops:80/api/webhook
    KUBECHECKS_ARGOCD_REPOSITORY_ENDPOINT: openshift-gitops-repo-server.openshift-gitops.svc.clsuter.local:8081
    KUBECHECKS_ARGOCD_REPOSITORY_INSECURE: "true"
    KUBECHECKS_FALLBACK_K8S_VERSION: "1.23.0"
    KUBECHECKS_LOG_LEVEL: debug
    KUBECHECKS_NAMESPACE: kubechecks
    KUBECHECKS_WEBHOOK_URL_BASE: https://kubechecks.apps.${PLATFORM_BASE_DOMAIN}
    ARGOCD_EXEC_TIMEOUT: 600s
    KUBECHECKS_OTEL_ENABLED: "false"
    KUBECHECKS_VCS_TYPE: "github"
    KUBECHECKS_VCS_USERNAME: "vikaspogu"
    KUBECHECKS_VCS_EMAIL: "vikaspoguadf@gmail.com"
    KUBECHECKS_TIDY_OUTDATED_COMMENTS_MODE: "hide" # other options delete

deployment:
  annotations:
    reloader.stakater.com/auto: "true"

  podAnnotations: {}

  args: []

  # Default values for kubechecks.
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 200m

  revisionHistoryLimit: 10
  replicaCount: 1

  image:
    pullPolicy: Always
    name: "ghcr.io/zapier/kubechecks"
    tag: "v2.5.2"

  imagePullSecrets: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podSecurityContext:
    {}
    # runAsNonRoot: true
    # runAsUser: 32123
    # fsGroup: 32123

  securityContext:
    # allowPrivilegeEscalation: true
    privileged: true
    # capabilities:
    #   drop:
    #     - ALL
    # readOnlyRootFilesystem: false

  env: []

  envFrom:
    - secretRef:
        name: kubechecks

  startupProbe:
    failureThreshold: 30
    periodSeconds: 10

  livenessProbe:
    failureThreshold: 30
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5

  readinessProbe:
    failureThreshold: 30
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5

serviceAccount:
  create: true
  enabled: true
  name: '{{ include "kubechecks.fullname" . }}'

service:
  create: true
  type: ClusterIP
  port: 8080
  name: http

ingress:
  create: true
  className: ""
  annotations:
    route.openshift.io/termination: "edge"
  hosts:
    kubechecks.apps.${PLATFORM_BASE_DOMAIN}:
      paths:
        - path: "/"
          pathType: Prefix
