---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-notifications-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        pushover-user: "{{.user_key}}"
        pushover-token: "{{.ARGOCD_API_KEY}}"
        appID: "{{ .AUTH_ORG_APP_ID }}"
        installationID: "{{ .APP_INSTALLATION_ID }}"
        github-privateKey: |
          {{ .AUTH_ORG1_PRIVATE_KEY }}
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: developer-hub
        metadataPolicy: None
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: Pushover
        metadataPolicy: None
