Kind: Secret
apiVersion: v1
metadata:
  name: environment-variables
type: Opaque
stringData:
  CLUSTER_BASE_DOMAIN: ENC[AES256_GCM,data:PIMu5F0Vx0p/G4PrrW2JTBw=,iv:1fp1p4mLppsmBObohMNs5qLAzLU9vHsb0C/3P49cjak=,tag:esEtIYce+qewqMpi9apSWw==,type:str]
sops:
  age:
    - recipient: age1ulfhs490lug3kres5qm5kfdmpqmcrwsfsc03eln0s3xffndnrcwq5u86tt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVjIzbThMbkV4ZzQwbWZq
        NTVsSDRLWnhMbUxtOHVYNCszMUdVL3VEZjEwCndPNW12NEFtZVJoVkxGS005MlNG
        dW1Idjk1bEEzQUVOOXJZTEFYQW5xZU0KLS0tIGl4dlhxdkY2M3JERWdtOE1jYStn
        ZGZ5dGthMG54YXlUY1MzNzgxbDlkaGMKhZ9EQRRBncqZH3NYf7/5FK9ab5mqy2Lr
        6nQHlAsa+T5ZFrIjh00Uy9C0L2+sfQqfPFnJ+f02+onH09FcRWLYnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-08T15:51:11Z"
  mac: ENC[AES256_GCM,data:Ilft2soQ33vwd+8R8N0TQsZXI/iZqfkcQ3esFLa4gLeaQxBFRF7t9aGlAVU3uzoxAtAh/38c5SY90T4JsGkrx+i3GHUSZlVuEIYLSMn/6VeTN9uhJOTVxKTBH34TDq9YywBQUkaTE3s7UBk+2XxgWAFz/6YoOQ0joesCrkzAYlg=,iv:s6z/tkEkMu+2Q6qUaUtz/zn8JA/qlz8uUbof4qNUvRk=,tag:JrUXc1yzcETlOnPl2+LQ1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
