apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: environment-variables
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: environment-variables
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        CLUSTER_DOMAIN: "{{ .DUCKDNS_DOMAIN_NAME }}"
  dataFrom:
    - extract:
        key: homepage
