---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-websecure
  namespace: argocd-app
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.omv-loki.vikaspogu.internal`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls: {}
