---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: environment-variables-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./environment-variables.sops.yaml
