---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - ./rb.yaml
  - ./service.yaml
  - ./deployment.yaml
generators:
  - ./secret-generator.yaml
