---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: onepassword-connect-secret
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secret.sops.yaml
