---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml

helmCharts:
  - name: reloader
    releaseName: reloader
    namespace: reloader
    repo: https://stakater.github.io/stakater-charts
    version: "2.2.0"
    valuesInline:
      nameOverride: reloader
      fullnameOverride: reloader
      reloader:
        isOpenshift: true

patches:
  - target:
      kind: Deployment
      name: reloader
    patch: |-
      - op: replace
        path: /spec/template/spec/securityContext
        value: {}
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                divisor: '0'
                resource: limits.cpu
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                divisor: '0'
                resource: limits.memory
