---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: external-secret-store
spec:
  rules:
    - name: external-secret-store
      match:
        any:
          - resources:
              kinds:
                - Namespace
              operations:
                - CREATE
              selector:
                matchLabels:
                  team: "?*"
                  cluster: "?*"
      generate:
        synchronize: true
        apiVersion: external-secrets.io/v1beta1
        kind: SecretStore
        namespace: "{{request.object.metadata.name}}"
        name: "{{request.object.metadata.name}}-secret-store"
        data:
          metadata:
            labels:
              created-by: kyverno
              generated-for: "{{request.object.metadata.name}}-{{request.object.metadata.labels.team}}"
          spec:
            provider:
              vault:
                auth:
                  kubernetes:
                    mountPath: "{{request.object.metadata.labels.cluster}}/{{request.object.metadata.labels.team}}/{{request.object.metadata.name}}"
                    role: "{{request.object.metadata.name}}"
                    serviceAccountRef:
                      name: default
                path: "{{request.object.metadata.labels.cluster}}/{{request.object.metadata.labels.team}}/{{request.object.metadata.name}}"
                server: "http://vault.vault.svc.cluster.local:8200"
                version: v1
