---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Delete=false
  name: cluster
spec:
  servingCerts:
    namedCertificates:
      - names:
          - api.${PLATFORM_BASE_DOMAIN}
        servingCertificate:
          name: openshift-api-certificate
