{{- $releaseLabels := include "project-onboarding.labels" . -}}
{{- $values := .Values -}}
{{- range $key, $apps := .Values.apps}}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $key }}-deploy-app-set
  namespace: {{ $values.namespace }}
  labels:
    {{- $releaseLabels | nindent 4 }}
    {{ $values.team }}-gitops: {{$key}}
spec:
  generators:
    - git:
        repoURL: {{$apps.tenantGitops.repo}}
        revision: HEAD
        files:
          - path: "{{$apps.tenantGitops.path}}/deploy/*.yaml"
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: {{ $key }}-{{`{{ .path.filename | splitList "-" | first }}` }}
      labels:
        {{ $values.team }}-gitops: {{$key}}
    spec:
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{ $values.namespace | splitList "-" | first }}-{{`{{ .path.filename | splitList "-" | first }}` }}'
      project: {{ $key }}
      sources:
        - helm:
            releaseName: {{$key}}
            valueFiles:
              - "$values/{{`{{ .path.path }}/{{.path.filename}}`}}"
          path: charts/deploy
          repoURL: "{{$apps.helmChartRepo}}"
          targetRevision: main
        - ref: values
          repoURL: {{$apps.tenantGitops.repo}}
          targetRevision: main
      syncPolicy:
        automated: {}
        syncOptions:
          - SkipDryRunOnMissingResource=true
          - Validate=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
          - Prune=true
{{- end }}
