---
replicaCount: 1
image:
  repository: docker.io/cloudflare/cloudflared
  tag: "2025.2.1"
cloudflared:
  tunnelID: "76cace65-155d-4719-9b29-4bfb94f5c013"
  existingSecret: cloudflared
  ingress:
    - hostname: "console-openshift-console.apps.dev-acm.v3socp.boo"
      originRequest:
        noTLSVerify: true
      service: https://router-internal-default.openshift-ingress.svc.cluster.local
    - hostname: "pipelines-as-code-controller-openshift-pipelines.apps.dev-acm.v3socp.boo"
      originRequest:
        noTLSVerify: true
      service: https://router-internal-default.openshift-ingress.svc.cluster.local
    - hostname: "openshift-gitops-server-openshift-gitops.apps.dev-acm.v3socp.boo"
      originRequest:
        noTLSVerify: true
      service: https://router-internal-default.openshift-ingress.svc.cluster.local
    - service: http_status:404
