---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: developer-hub-user
  namespace: developer-hub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: developer-hub-user
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "[a-z-0-9]*-cicd"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "[a-z-0-9]*-cicd"
      data:
        password: "{{ .ARGOCD_DEV_HUB_PASSWORD }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: developer-hub
        metadataPolicy: None
