---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhdh-pull-secret
  namespace: developer-hub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rhdh-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .quay_pull_secret | toString }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: redhat-pull-secret
        metadataPolicy: None
