---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pipeline-build-secret
  namespace: developer-hub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pipeline-build-secret
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "[a-z-0-9]*cicd[a-z-0-9]*"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "[a-z-0-9]*cicd[a-z-0-9]*"
      data:
        config.json: "{{ .quay_pull_secret | toString }}"
        rox_api_token: "{{.rox_api_token}}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: redhat-pull-secret
        metadataPolicy: None
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: developer-hub
        metadataPolicy: None
