---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: developer-hub
resources:
  - ./namespace.yaml
  - ./dynamic-plugin-pvc.yaml
  - ./backstage.yaml
  - ./externalsecret.yaml
  - ./externalsecret-pullsecret.yaml
  # - ./externalsecret-devhub-read.yaml
  # - ./externalsecret-pipeline-build.yaml
  - ./rolebindings.yaml
  - ./ocm-rolebindings.yaml
  - ./console-link.yaml
  # - ./aap-tools-deployment.yaml

configMapGenerator:
  - name: app-config-rhdh
    files:
      - app-config-rhdh.yaml=./app-config-rhdh.yaml
  - name: dynamic-plugins-rhdh
    files:
      - dynamic-plugins.yaml=./dynamic-plugins-rhdh.yaml
  - name: rbac-policy
    files:
      - rbac-policy.csv=./rbac-policy.csv
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    reloader.stakater.com/match: "true"
