---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhacs-operator
resources:
  - ./namespace.yaml

helmCharts:
  - name: operators-installer
    releaseName: rhacs-operator
    namespace: rhacs-operator
    repo: https://redhat-cop.github.io/helm-charts
    version: "3.1.1"
    valuesInline:
      operators:
        - channel: stable
          installPlanApproval: Automatic
          name: rhacs-operator
          source: redhat-operators
          sourceNamespace: openshift-marketplace
      operatorGroups:
        - createNamespace: false
