---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pipelines-as-code-secret
  namespace: openshift-pipelines
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pipelines-as-code-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        annotations:
          appUrl: "https://github.com/apps/openshift-pipelines-vpogu"
          appName: "OpenShift Pipelines VPogu"
      data:
        github-private-key: "{{ .PRIVATE_KEY }}"
        github-application-id: "{{ .APP_ID }}"
        webhook.secret: "{{ .WEBHOOK_SECRET }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: ocp-pipelines
        metadataPolicy: None
