---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        webhook.github.secret: "{{.WEBHOOK_SECRET}}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd
        metadataPolicy: None
