---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-wildcard
  namespace: openshift-ingress
spec:
  secretName: openshift-wildcard-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.apps.${PLATFORM_BASE_DOMAIN}"
  dnsNames:
    - "*.apps.${PLATFORM_BASE_DOMAIN}"
