apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:hostmount-anyuid
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - hostmount-anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:hostmount-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostmount-anyuid
subjects:
  - kind: ServiceAccount
    name: nfs-subdir-external-provisioner
    namespace: openshift-nfs-storage
