---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhdh-secrets
  namespace: developer-hub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rhdh-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GITHUB_APP_CLIENT_ID: "{{ .GITHUB_APP_CLIENT_ID }}"
        GITHUB_APP_CLIENT_SECRET: "{{ .GITHUB_APP_CLIENT_SECRET }}"
        GH_TOKEN: "{{ .GH_TOKEN }}"
        ARGOCD_ADMIN_PASSWORD: "{{ .ARGOCD_ADMIN_PASSWORD }}"
        ARGOCD_TOKEN: "{{ .ARGOCD_TOKEN }}"
        BACKEND_SECRET: "{{ .BACKEND_SECRET }}"
        ARGOCD_DEV_HUB_PASSWORD: "{{ .ARGOCD_DEV_HUB_PASSWORD }}"
        AUTH_ORG_APP_ID: "{{ .AUTH_ORG_APP_ID }}"
        AUTH_ORG_CLIENT_ID: "{{ .AUTH_ORG_CLIENT_ID }}"
        AUTH_ORG_CLIENT_SECRET: "{{ .AUTH_ORG_CLIENT_SECRET }}"
        AUTH_ORG1_PRIVATE_KEY: "{{ .AUTH_ORG1_PRIVATE_KEY }}"
        AUTH_ORG_WEBHOOK_SECRET: "{{ .AUTH_ORG_WEBHOOK_SECRET }}"
        SONARQUBE_URL: "{{.SONAR_URL}}"
        SONARQUBE_TOKEN: "{{.SONAR_AUTH_TOKEN}}"
        AAP_AUTH_TOKEN: "{{.AAP_TOKEN}}"
        AAP_URL: "{{.AAP_URL}}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: developer-hub
        metadataPolicy: None
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: sonarqube
        metadataPolicy: None
