---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
  namespace: openshift-cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cert-manager-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: cloudflare
        property: api_key
