---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: rancher-app
  labels:
    app.kubernetes.io/instance: rancher
    app.kubernetes.io/name: rancher
spec:
  repo: https://releases.rancher.com/server-charts/stable
  chart: rancher
  targetNamespace: rancher-app
  valuesContent: |-
    hostname: "rancher.omv-loki.vikaspogu.internal"
    replicas: 1
    rancherImageTag: v2.12-head@sha256:55d6e2fe1fb13408398dc03028693b62f7c3e885433e656edc70611fa7e302c8
    ingress:
      enabled: false
