---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        .gitconfig: |
          [credential "https://github.com"]
            helper = store
        .git-credentials: |
          https://{{.GH_USER}}:{{.GH_TOKEN}}@github.com
        token: "{{.TOKEN}}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: ocp-pipelines
        metadataPolicy: None
