---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-pull-secret
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  labels:
    {{- include "create-cluster.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: {{ .Values.clusterName }}-pull-secret
    creationPolicy: Owner
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: redhat-pull-secret
        property: pull-secret
        metadataPolicy: None
