---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-install-config
  namespace: {{ .Values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  labels:
    {{- include "create-cluster.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: vcenter
        metadataPolicy: None
  target:
    name: {{ .Values.clusterName }}-install-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        install-config.yaml: |
          apiVersion: v1
          metadata:
            name: {{ .Values.clusterName }}
          baseDomain: {{ .Values.baseDomain }}
          controlPlane:
            hyperthreading: Enabled
            name: master
            replicas: {{ .Values.masterNode.replicas }}
            platform:
              vsphere:
                cpus:  {{ .Values.masterNode.cpus }}
                coresPerSocket:  {{ .Values.masterNode.corePerSocket }}
                memoryMB:  {{ .Values.masterNode.memoryMB }}
                osDisk:
                  diskSizeGB: {{ .Values.masterNode.diskSizeGB }}
          compute:
          - hyperthreading: Enabled
            name: 'worker'
            replicas: {{ .Values.workerNode.replicas }}
            platform:
              vsphere:
                cpus:  {{ .Values.workerNode.cpus }}
                coresPerSocket:  {{ .Values.workerNode.corePerSocket }}
                memoryMB:  {{ .Values.workerNode.memoryMB }}
                osDisk:
                  diskSizeGB: {{ .Values.workerNode.diskSizeGB }}
          networking:
            networkType: OVNKubernetes
            clusterNetwork:
            - cidr: 10.128.0.0/14
              hostPrefix: 23
            machineNetwork:
            - cidr: 10.0.0.0/16
            serviceNetwork:
            - 172.30.0.0/16
          platform:
            vsphere:
              vCenter: {{ .Values.vcenter.server }}
              username: '{{`{{.username}}`}}'
              password: '{{`{{.password}}`}}'
              datacenter: {{ .Values.vcenter.datacenter }}
              defaultDatastore: {{ .Values.vcenter.datastore }}
              cluster: {{ .Values.vcenter.cluster }}
              apiVIP: {{ .Values.vips.api }}
              ingressVIPs:
              - {{ .Values.vips.ingress }}
              network: {{ .Values.vcenter.network }}
          pullSecret: "" # skip, hive will inject based on it's secrets
