---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-ssh-private-key
  namespace: {{ .Values.clusterName }}
  labels:
    {{- include "create-cluster.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: {{ .Values.clusterName }}-ssh-private-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ssh-privatekey: |
          '{{`{{.SSH_PRIVATE_KEY_MACOS}}`}}'
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: vcenter
        metadataPolicy: None
