---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.clusterName }}-vsphere-certs
  namespace: {{ .Values.clusterName }}
  labels:
    {{- include "create-cluster.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: {{ .Values.clusterName }}-vsphere-certs
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        .cacert: '{{`{{.CA_CERT}}`}}'
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: vcenter
        metadataPolicy: None
