---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: vSphere
    name: {{ .Values.clusterName }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'default'
    gitops: 'true'
    {{- include "create-cluster.labels" . | nindent 4 }}
  name: {{ .Values.clusterName }}
spec:
  hubAcceptsClient: true
