---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gh-pr
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.html_url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-revision
      value: $(body.pull_request.head.ref)
    - name: pr-number
      value: $(body.pull_request.number)
    - name: pr-url
      value: $(body.pull_request.html_url)
    - name: head-sha
      value: $(body.pull_request.head.sha)
    - name: git-repo-full-name
      value: $(body.pull_request.head.repo.full_name)
