---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-workflows
  namespace: openshift-gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argo-workflows-sso
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "{{ .CLIENT_ID }}"
        client-secret: "{{ .CLIENT_SECRET }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-workflows
        metadataPolicy: None
