---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
resources:
  - ./namespace.yaml
helmCharts:
  - name: operators-installer
    releaseName: cloudnative-pg
    namespace: cloudnative-pg
    repo: https://redhat-cop.github.io/helm-charts
    version: "3.2.0"
    valuesInline:
      operators:
        - channel: stable-v1
          installPlanApproval: Automatic
          name: cloudnative-pg
          source: certified-operators
          sourceNamespace: openshift-marketplace
      operatorGroups:
        - createNamespace: false
