---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: keycloak-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .PG_USER }}"
        password: "{{ .PG_PASS }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: developer-hub
        metadataPolicy: None
