apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../groups/all
  - ../../groups/dev

helmGlobals:
  chartHome: ../../helm/charts

helmCharts:
  - name: argocd-app-of-app
    valuesInline:
      default:
        app:
          finalizers:
            - resources-finalizer.argocd.argoproj.io
          enabled: true
          enableAutoSync: true
          autoSyncPrune: true
          project: cluster-config
          labels:
            app-source: cluster-vsphere
            repo: cluster-config
          destination:
            namespace: openshift-gitops
            server: https://kubernetes.default.svc
          source:
            repoURL: https://github.com/Vikaspogu/openshift-multicluster.git
            targetRevision: HEAD
          syncOptions:
            - ApplyOutOfSyncOnly=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
            - ServerSideApply=true
            - FailOnSharedResource=true
            - RespectIgnoreDifferences=true
            - CreateNamespace=false
          syncPolicyRetry:
            limit: -1
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 10m
    additionalValuesFiles:
      # - ./acm.yaml
      # - ./alertmanager.yaml
      - ./cert-manager.yaml
      - ./cloudflared.yaml
      - ./external-secrets.yaml
      - ./oauth.yaml
      - ./onepassword-connect.yaml
      - ./openshift-gitops.yaml
      # - ./openshift-pipelines.yaml
      - ./reflector.yaml
      - ./reloader.yaml
      - ./rhdh.yaml
      - ./web-terminal.yaml
      # - ./sso.yaml
    namespace: openshift-gitops

patches: []
