---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops

helmCharts:
  - name: argo-events
    releaseName: argo-events
    namespace: openshift-gitops
    repo: https://argoproj.github.io/argo-helm
    version: "2.4.16"
    valuesInline:
      openshift: true
