---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: image-registry-private-configuration-user
  namespace: openshift-image-registry
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: image-registry-private-configuration-user
    creationPolicy: Owner
  data:
    - secretKey: REGISTRY_STORAGE_S3_ACCESSKEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: minio
        property: access_key
    - secretKey: REGISTRY_STORAGE_S3_SECRETKEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: minio
        property: secret_key
