---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: synology-csi-secret
  namespace: synology-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: synology-csi-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-info.yaml: |
          clients:
            - host: {{.NAS_IP}}
              https: false
              password: {{.password}}
              port: 5000
              username: {{.username}}
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: nas-csi
        metadataPolicy: None
