---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "[a-z-0-9]*-hcp"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "[a-z-0-9]*-hcp"
      data:
        clientSecret: "{{ .CLIENT_SECRET_PROXMOX }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: openshift
        metadataPolicy: None
