---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: github-oauth-config
  namespace: openshift-devspaces
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: github-oauth-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/part-of: che.eclipse.org
          app.kubernetes.io/component: oauth-scm-configuration
        annotations:
          che.eclipse.org/oauth-scm-server: github
          che.eclipse.org/scm-server-endpoint: https://github.com
          che.eclipse.org/scm-github-disable-subdomain-isolation: "false"
      data:
        id: "{{.client_id}}"
        secret: "{{.client_secret}}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: devspaces
        metadataPolicy: None
