apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acm-policies

resources:
  - placement.yaml
  - managedclustersetbinding.yaml

generators:
  - policy-generator-config.yaml
