---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_LONGITUDE
      remoteRef:
        key: homepage
        property: LONGITUDE
    - secretKey: HOMEPAGE_VAR_LATITUDE
      remoteRef:
        key: homepage
        property: LATITUDE
