---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        Kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets
