---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cluster-secret-store.yaml

helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    namespace: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.20.3
    valuesInline:
      installCRDs: true
