apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../groups/all
  - ../../groups/dev

helmGlobals:
  chartHome: ../../helm/charts

helmCharts:
  - name: argocd-app-of-app
    valuesInline:
      default:
        app:
          enabled: true
          enableAutoSync: true
          autoSyncPrune: true
          project: cluster-config
          labels:
            app-source: cluster-proxmox
            repo: cluster-config
          destination:
            namespace: openshift-gitops
            server: https://kubernetes.default.svc
          source:
            repoURL: https://github.com/Vikaspogu/openshift-multicluster.git
            targetRevision: HEAD
          syncOptions:
            - ApplyOutOfSyncOnly=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
            - ServerSideApply=true
            - FailOnSharedResource=true
            - RespectIgnoreDifferences=true
            - CreateNamespace=false
          syncPolicyRetry:
            limit: 5
            backoff:
              duration: 1m
              factor: 2
              maxDuration: 5m
    additionalValuesFiles:
      - ./acm.yaml
      - ./alertmanager.yaml
      - ./cert-manager.yaml
      - ./cloudflared.yaml
      - ./developer-hub.yaml
      - ./devspaces.yaml
      - ./external-secrets.yaml
      - ./image-registry.yaml
      - ./kubernetes-imagepuller.yaml
      # - ./logging.yaml
      - ./lvm.yaml
      # - ./metallb.yaml
      # - ./nmstate.yaml
      - ./oauth.yaml
      - ./onepassword-connect.yaml
      - ./openshift-gitops.yaml
      - ./openshift-pipelines.yaml
      - ./reflector.yaml
      - ./reloader.yaml
      - ./synology-csi.yaml
      # - ./virtualization.yaml
      # - ./volsync.yaml
      - ./web-terminal.yaml
    namespace: openshift-gitops

patches: []
