applications:
  openshift-logging-operator:
    annotations:
      argocd.argoproj.io/sync-wave: "5"
    destination:
      namespace: openshift-logging
    source:
      path: components/openshift-logging-operator
  log-forwarder-config:
    annotations:
      argocd.argoproj.io/sync-wave: "25"
    destination:
      namespace: openshift-logging
    source:
      path: components/log-forwarder-config
