---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "vikaspoguadf@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: "vikaspoguadf@gmail.com"
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - ${CLUSTER_BASE_DOMAIN}
