---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: oauth-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        clientSecret: "<REPLACE>"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: openshift
        metadataPolicy: None
