---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: authentik
      openID:
        extraScopes:
          - email
          - profile
        extraAuthorizeParameters:
          include_granted_scopes: "true"
        claims:
          groups:
            - groups
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: "<REPLACE>"
        clientSecret:
          name: oauth-secret
        issuer: "<REPLACE>"
      type: OpenID
