---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: authentik
      openID:
        extraScopes:
          - email
          - profile
        extraAuthorizeParameters:
          include_granted_scopes: "true"
        claims:
          groups:
            - groups
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: oztcmkQD4zn8D68KYoRNbyXPKmo6brfu8dMHXyGEr4WdA
        clientSecret:
          name: oauth-secret
        issuer: "https://id.vikaspogu.com/application/o/openshift-vsphere"
      type: OpenID
