---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: configmap-copy-policy
spec:
  object-templates-raw: |
    {{- range $var := ["test", "test1", "test2"] }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: configmap-copy
          namespace: default
        data:
          key: '{{ $var }}'
      {{- end }}
  remediationAction: enforce
  pruneObjectBehavior: DeleteAll
