---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: configmap-copy-policy
spec:
  object-templates-raw: |
    {{- range $var := list "zone1" "ingress" "ops" }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: configmap-copy-{{$var}}
          namespace: acm-policies
        data:
          cpu: '{{hub fromConfigMap "acm-policies" (printf "machineset-%s" $var) "cpu" | toInt hub}}'
      {{- end }}
  remediationAction: enforce
  pruneObjectBehavior: DeleteAll
