apiVersion: v1
kind: ConfigMap
metadata:
  name: machineset
data:
  ingress-cpu: "15"
  zone1-cpu: "25"
  ops-cpu: "35"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: machineset-zone1
data:
  cpu: "15"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: machineset-ingress
data:
  cpu: "20"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: machineset-ops
data:
  cpu: "25"
