---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: configmap-copy-policy
spec:
  object-templates-raw: |
    {{hub- range $var := list "zone1" "ingress" "ops" hub}}
    {{hub- $var_cpu := (printf "%s-cpu" $var) hub}}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: configmap-copy-{{hub $var hub}}
          namespace: acm-policies
        data:
          cpu: '{{hub index (lookup "v1" "ConfigMap" "acm-policies" "machineset").data $var_cpu hub}}'
    {{hub- end hub}}
  remediationAction: enforce
  pruneObjectBehavior: DeleteAll
# {{- $cm := lookup "v1" "ConfigMap" "acm-policies" (printf "machineset-%s" $var) }}
# {{- $cpu := $cm.data.cpu }}
