---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: configmap-copy-policy
spec:
  object-templates-raw: |
    {{- range $var := list "zone1" "ingress" "ops" }}
    {{- $cm_name := printf "machineset-%s" $var }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: configmap-copy-{{$var}}
          namespace: acm-policies
        data:
          cpu: '{{hub (lookup "v1" "ConfigMap" "acm-policies" $cm_name).data.cpu hub}}'
      {{- end }}
  remediationAction: enforce
  pruneObjectBehavior: DeleteAll
