---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: operators-installer
    releaseName: web-terminal-operator
    namespace: web-terminal-operator
    repo: https://redhat-cop.github.io/helm-charts
    version: "3.3.0"
    valuesInline:
      operators:
        - channel: <REPLACE>
          installPlanApproval: Automatic
          name: web-terminal
          source: redhat-operators
          sourceNamespace: openshift-marketplace
      operatorGroups:
        - createNamespace: true
