---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-config-operator
  namespace: vault-config-operator
spec:
  channel: <REPLACE>
  installPlanApproval: Manual
  name: vault-config-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: VAULT_ADDR
        value: <vault-addr>
      - name: VAULT_SKIP_VERIFY
        value: "true"
