---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./external-secret.yaml
  - ./ingress-route.yaml
helmCharts:
  - name: app-template
    releaseName: garage
    repo: https://bjw-s-labs.github.io/helm-charts
    version: "4.2.0"
    valuesFile: values.yaml
