controllers:
  garage:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: dxflrs/garage
          tag: v2.1.0@sha256:4c9b34c113e61358466e83fd6e7d66e6d18657ede14b776eb78a93ee8da7cf6a
        env:
          TZ: "America/New_York"
        envFrom:
          - secretRef:
              name: garage-secret
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 512Mi
      webui:
        image:
          repository: khairul169/garage-webui
          tag: 1.1.0@sha256:17c793551873155065bf9a022dabcde874de808a1f26e648d4b82e168806439c
        env:
          API_BASE_URL: "http://garage.default.svc.cluster.local:3903"
          S3_ENDPOINT_URL: "http://garage.default.svc.cluster.local:3900"
          API_ADMIN_KEY: &apiKey
            valueFrom:
              secretKeyRef:
                name: garage-secret
                key: GARAGE_ADMIN_TOKEN
        envFrom:
          - secretRef:
              name: garage-secret
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 128Mi
service:
  app:
    ports:
      s3:
        port: 3900
      api:
        port: 3903
      webui:
        port: 3909

persistence:
  data:
    type: hostPath
    hostPath: /srv/dev-disk-by-uuid-9d2e4cb9-8825-4168-8153-e020ee524474/storage0/garage
    globalMounts:
      - path: /data
  meta:
    type: hostPath
    hostPath: /srv/dev-disk-by-uuid-9d2e4cb9-8825-4168-8153-e020ee524474/storage0/garage-meta
    globalMounts:
      - path: /meta

  config:
    enabled: true
    type: configMap
    name: garage-configmap
    globalMounts:
      - path: /etc/garage.toml
        subPath: configuration.toml
