---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-secret-reader
spec:
  rules:
    - name: policy-secret-reader
      match:
        any:
          - resources:
              kinds:
                - Namespace
              operations:
                - CREATE
              selector:
                matchLabels:
                  team: "?*"
                  cluster: "?*"
      generate:
        synchronize: true
        apiVersion: redhatcop.redhat.io/v1alpha1
        kind: Policy
        namespace: vault-admin
        name: "{{request.object.metadata.name}}"
        data:
          metadata:
            labels:
              created-by: kyverno
              generated-for: "{{request.object.metadata.name}}-{{request.object.metadata.labels.team}}"
          spec:
            authentication:
              path: kubernetes
              role: vault-admin
            policy: |
              path "{{request.object.metadata.labels.cluster}}/{{request.object.metadata.labels.team}}/{{request.object.metadata.name}}/*" {
                capabilities = ["read"]
              }
