---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: devlake
  namespace: apache-devlake
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: devlake
    creationPolicy: Owner
  data:
    - secretKey: ENCRYPTION_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: devlake
        property: ENCRYPTION_SECRET
    - secretKey: admin-user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: devlake
        property: grafana_user
    - secretKey: admin-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: devlake
        property: grafana_password
    - secretKey: user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: devlake
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: devlake
        property: password
