---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred
  namespace: apache-devlake
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: regcred
    creationPolicy: Owner
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        property: .dockerconfigjson
        key: ghrc_regcred
