---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-main
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by: ["alertname", "job"]
            group_interval: 10m
            group_wait: 1m
            receiver: webhook
            repeat_interval: 12h
            routes:
              - receiver: "null"
                matchers:
                  - alertname =~ "InfoInhibitor"
              - receiver: webhook
                continue: true
                mute_time_intervals:
                  - offhours
                matchers:
                  - severity = "critical"
          inhibit_rules:
            - equal: ["alertname", "namespace"]
              source_matchers:
                - severity = "critical"
              target_matchers:
                - severity = "warning"
          time_intervals:
            - name: offhours
              time_intervals:
                - times:
                    - start_time: 07:00
                      end_time: 17:00
                  weekdays: ['monday:friday']
                  location: "America/New_York"
          receivers:
            - name: "null"
            - name: webhook
              webhook_configs:
                - url: "{{ .WEBHOOK }}"
                  send_resolved: true
  dataFrom:
    - extract:
        key: gotify
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
