---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-main
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by: ["alertname", "job"]
            group_interval: 10m
            group_wait: 1m
            receiver: pushover
            repeat_interval: 12h
            routes:
              - receiver: "null"
                matchers:
                  - alertname =~ "InfoInhibitor"
              - receiver: pushover
                continue: true
                mute_time_intervals:
                  - offhours
                matchers:
                  - severity = "critical"
          inhibit_rules:
            - equal: ["alertname", "namespace"]
              source_matchers:
                - severity = "critical"
              target_matchers:
                - severity = "warning"
          time_intervals:
            - name: offhours
              time_intervals:
                - times:
                    - start_time: 07:00
                      end_time: 17:00
                  weekdays: ['monday:friday']
                  location: "America/New_York"
          receivers:
            - name: "null"
            - name: pushover
              pushover_configs:
                - html: true
                  message: |-
                    {{ "{{-" }} range .Alerts {{ "}}" }}
                      {{ "{{-" }} if ne .Annotations.description "" {{ "}}" }}
                        {{ "{{" }} .Annotations.description {{ "}}" }}
                      {{ "{{-" }} else if ne .Annotations.summary "" {{ "}}" }}
                        {{ "{{" }} .Annotations.summary {{ "}}" }}
                      {{ "{{-" }} else if ne .Annotations.message "" {{ "}}" }}
                        {{ "{{" }} .Annotations.message {{ "}}" }}
                      {{ "{{-" }} else {{ "}}" }}
                        Alert description not available
                      {{ "{{-" }} end {{ "}}" }}
                      {{ "{{-" }} if gt (len .Labels.SortedPairs) 0 {{ "}}" }}
                        <small>
                        {{ "{{-" }} range .Labels.SortedPairs {{ "}}" }}
                          <b>{{ "{{" }} .Name {{ "}}" }}:</b> {{ "{{" }} .Value {{ "}}" }}
                        {{ "{{-" }} end {{ "}}" }}
                        </small>
                      {{ "{{-" }} end {{ "}}" }}
                    {{ "{{-" }} end {{ "}}" }}
                  priority: |-
                    {{ "{{" }} if eq .Status "firing" {{ "}}" }}1{{ "{{" }} else {{ "}}" }}0{{ "{{" }} end {{ "}}" }}
                  send_resolved: true
                  sound: gamelan
                  # ttl: 1d
                  title: >-
                    [{{ "{{" }} .Status | toUpper {{ "}}" }}{{ "{{" }} if eq .Status "firing" {{ "}}" }}:{{ "{{" }} .Alerts.Firing | len {{ "}}" }}{{ "{{" }} end {{ "}}" }}]
                    {{ "{{" }} .CommonLabels.alertname {{ "}}" }}
                  token: "{{ .OPENSHIFT_API_KEY }}"
                  url_title: View in Alertmanager
                  user_key: "{{ .user_key }}"
  dataFrom:
    - extract:
        key: Pushover
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
