---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-gotify
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-gotify-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GOTIFY_ENDPOINT: "{{.ENDPOINT}}"
        GOTIFY_TOKEN: "{{.OCP_TOKEN}}"
  dataFrom:
    - extract:
        key: gotify
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
