---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-monitoring
resources:
  - ./externalsecret.yaml
  - ./externalsecret-alertmanager.yaml
helmCharts:
  - name: app-template
    releaseName: alertmanager-gotify
    repo: https://bjw-s-labs.github.io/helm-charts
    version: "3.7.3"
    valuesFile: values.yaml
